### ISSUE TITLE
Permission to add Prosystem to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by inactive123** [gstanton/ProSystem1_3#3]
Hi there @gstanton,

we would like to seek your permission to include Prosystem as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by gstanton** [comment]
Yep, please include it.

**Comment by inactive123** [comment]
Thank you!
